/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/lib/Editor.vue')['default']
    Field: typeof import('./src/lib/Field.vue')['default']
    Input: typeof import('./src/lib/Input.vue')['default']
    WebCam: typeof import('./src/lib/webcam/WebCam.vue')['default']
    WebCamUI: typeof import('./src/lib/webcam/WebCamUI.vue')['default']
  }
}
